import type { ThemeConfig, ThemeName } from '@/types'

export const themes: Record<ThemeName, ThemeConfig> = {
  rose: {
    name: 'rose',
    label: 'Rose',
    colors: {
      primary: '#db2777',
      primaryHover: '#be185d',
      secondary: '#fdf2f8',
      accent: '#ec4899',
      background: '#ffffff',
      foreground: '#1a1a2e',
      muted: '#f9fafb',
      mutedForeground: '#6b7280',
      border: '#fce7f3',
      card: '#ffffff',
      cardForeground: '#1a1a2e',
    },
    fonts: {
      heading: "'Playfair Display', serif",
      body: "'Inter', sans-serif",
    },
    borderRadius: '0.75rem',
  },
  luxuryGold: {
    name: 'luxuryGold',
    label: 'Luxury Gold',
    colors: {
      primary: '#b8860b',
      primaryHover: '#9a7209',
      secondary: '#fff8e7',
      accent: '#d4a843',
      background: '#0a0a0a',
      foreground: '#f5f0e8',
      muted: '#1a1a1a',
      mutedForeground: '#a09880',
      border: '#333018',
      card: '#14140e',
      cardForeground: '#f5f0e8',
    },
    fonts: {
      heading: "'Cormorant Garamond', serif",
      body: "'Inter', sans-serif",
    },
    borderRadius: '0.5rem',
  },
  medical: {
    name: 'medical',
    label: 'Medical',
    colors: {
      primary: '#0891b2',
      primaryHover: '#067a96',
      secondary: '#ecfeff',
      accent: '#06b6d4',
      background: '#ffffff',
      foreground: '#0f172a',
      muted: '#f1f5f9',
      mutedForeground: '#64748b',
      border: '#e2e8f0',
      card: '#ffffff',
      cardForeground: '#0f172a',
    },
    fonts: {
      heading: "'Inter', sans-serif",
      body: "'Inter', sans-serif",
    },
    borderRadius: '0.375rem',
  },
  minimal: {
    name: 'minimal',
    label: 'Minimal',
    colors: {
      primary: '#18181b',
      primaryHover: '#27272a',
      secondary: '#f4f4f5',
      accent: '#71717a',
      background: '#fafafa',
      foreground: '#18181b',
      muted: '#f4f4f5',
      mutedForeground: '#71717a',
      border: '#e4e4e7',
      card: '#ffffff',
      cardForeground: '#18181b',
    },
    fonts: {
      heading: "'Inter', sans-serif",
      body: "'Inter', sans-serif",
    },
    borderRadius: '0',
  },
  organic: {
    name: 'organic',
    label: 'Organic',
    colors: {
      primary: '#16a34a',
      primaryHover: '#15803d',
      secondary: '#f0fdf4',
      accent: '#22c55e',
      background: '#fefce8',
      foreground: '#1a2e05',
      muted: '#f7fee7',
      mutedForeground: '#4a7c3f',
      border: '#dcfce7',
      card: '#ffffff',
      cardForeground: '#1a2e05',
    },
    fonts: {
      heading: "'DM Serif Display', serif",
      body: "'Inter', sans-serif",
    },
    borderRadius: '0.75rem',
  },
  beautyPremium: {
    name: 'beautyPremium',
    label: 'Beauty Premium',
    colors: {
      primary: '#c026d3',
      primaryHover: '#a21caf',
      secondary: '#fae8ff',
      accent: '#d946ef',
      background: '#fdf4ff',
      foreground: '#1a0a1e',
      muted: '#faf5ff',
      mutedForeground: '#6b21a8',
      border: '#f3e8ff',
      card: '#ffffff',
      cardForeground: '#1a0a1e',
    },
    fonts: {
      heading: "'Playfair Display', serif",
      body: "'Inter', sans-serif",
    },
    borderRadius: '1rem',
  },
}

export function getTheme(name: ThemeName): ThemeConfig {
  return themes[name] || themes.rose
}
