import { Product, Review, FAQ, Benefit, Feature, NavigationItem } from '../types';

export const NAVIGATION_ITEMS: NavigationItem[] = [
  {
    label: 'CİHAZLAR',
    href: '/#products',
    children: [
      { label: 'LED Terapiya Cihazları', href: '/#products?cat=led' },
      { label: 'Ultrases Təmizləyicilər', href: '/#products?cat=ultrasonic' },
      { label: 'Mikroaxın Liftinq', href: '/#products?cat=microcurrent' },
      { label: 'Göz Ətrafı Masajerlər', href: '/#products?cat=eye' },
    ],
  },
  {
    label: 'QULLUQ MƏHSULLARI',
    href: '/#skincare',
    isBadge: true,
    badgeText: 'YENİ',
  },
  {
    label: 'RİTUALLAR',
    href: '/#ritual',
  },
  {
    label: 'MÜŞTƏRİ RƏYLƏRİ',
    href: '/#reviews',
  },
  {
    label: 'HAQQIMIZDA',
    href: '/#about',
  },
  {
    label: 'FAQ / DƏSTƏK',
    href: '/#faq',
  },
];

export const VALUE_PROPS = [
  {
    id: 'prop-1',
    title: 'DƏRİ TİPİNİ TƏYİN ET',
    description: '1 dəqiqəlik testlə dərinizə ən uyğun qulluq rejimini seçin.',
    iconName: 'Sparkles',
    actionText: 'TESTƏ BAŞLA',
    href: '#quiz',
  },
  {
    id: 'prop-2',
    title: 'MÜKƏMMƏL CİHAZ TAPICI',
    description: 'Ehtiyaclarınıza uyğun Aluna texnologiyasını müəyyən edin.',
    iconName: 'Search',
    actionText: 'CİHAZLARI MÜQAYİSƏ ET',
    href: '#compare',
  },
  {
    id: 'prop-3',
    title: 'VİRTUAL MƏSLƏHƏTÇİ',
    description: 'Süni intellekt dəstəkli dəri analizi və dərhal məsləhətlər.',
    iconName: 'Bot',
    actionText: 'ANALİZƏ BAŞLA',
    href: '#ai-advisor',
  },
  {
    id: 'prop-4',
    title: 'CANLI GÖZƏLLİK EKSPERTİ',
    description: 'Bizim peşəkar kosmetoloqlarımızla ödənişsiz onlayn konsultasiya.',
    iconName: 'PhoneCall',
    actionText: 'GÖRÜŞ TƏYİN ET',
    href: '#consultation',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'aluna-radiance-pro',
    name: 'ALUNA Radiance Pro',
    subtitle: '7-si-1-də LED İşıq Terapiyası və Mikroaxın Liftinq Cihazı',
    description: 'Aluna Radiance Pro ev şəraitində peşəkar salon nəticələri əldə etmək üçün hazırlanmış premium gözəllik cihazıdır. 7 fərqli işıq dalğası (LED), mikroaxın liftinqi (EMS), termal masaj və sonik vibrasiya sayəsində dərini cavanlaşdırır, qırışları hamarlayır, akne və ləkələri nəzərəçarpacaq dərəcədə azaldır.',
    price: 249.00,
    originalPrice: 349.00,
    rating: 4.9,
    reviewsCount: 128,
    images: [
      'https://picsum.photos/id/1025/800/1000', // Premium facial devices mockup styling
      'https://picsum.photos/id/1026/800/1000',
      'https://picsum.photos/id/1027/800/1000',
    ],
    category: 'LED Terapiya',
    benefits: [
      'Kollagen sintezini sürətləndirərək qırışları dərindən doldurur',
      'Mikroaxınlar (EMS) vasitəsilə üz əzələlərini sıxlaşdırır və liftinq effekti verir',
      'Göy LED işığı sayəsində sızanaqları və iltihabı aradan qaldırır',
      'İsti kompres rejimində serum və maskaların təsirini 3 qat artırır',
    ],
    howToUse: 'Hər gün təmizlənmiş üz dərisinə Aluna nəmləndirici serumu tətbiq edin. Cihazı yandırın və istədiyiniz rejimi (məs. Qırmızı LED + EMS) seçin. Üz xətləri boyu aşağıdan yuxarıya doğru, hər nahiyədə 3-5 dəqiqə ərzində yüngül masaj hərəkətləri ilə sürüşdürün. Cihaz avtomatik taymerlə təchiz edilmişdir.',
    ingredients: 'Cihaz tibbi dərəcəli hipoallergik paslanmayan polad başlıq və yüksək keyfiyyətli, ekoloji cəhətdən təmiz ABS korpusdan hazırlanmışdır. Dəriyə tam zərərsizdir, beynəlxalq CE və RoHS sertifikatlarına malikdir.',
    tags: ['Ən Çox Satılan', 'Premium Qulluq'],
    isNew: true,
    tryOnEnabled: true,
    shades: [
      { name: 'Mirvari Ağ', colorHex: '#F5F5F0', isHot: true, label: 'Pearl White' },
      { name: 'Səhra Qızılı', colorHex: '#E5C0A0', label: 'Sahara Gold' },
      { name: 'Zərif Çəhrayı', colorHex: '#ECD5D5', label: 'Soft Pink' },
    ],
  },
  {
    id: 'aluna-ultrasonic-clean',
    name: 'ALUNA Sonic Deep Cleanser',
    subtitle: 'Ultrases Sonik Üz Təmizləyici və Spatula Cihazı',
    description: 'Dərinin ən dərin qatlarında yığılmış makiyaj qalıqlarını, qara nöqtələri və artıq sebumu saniyələr içində təmizləyən ultrasəs texnologiyalı spatula. Ölü hüceyrələri yumşaq şəkildə soyaraq dərini hamar və ipək kimi edir.',
    price: 129.00,
    originalPrice: 189.00,
    rating: 4.8,
    reviewsCount: 94,
    images: [
      'https://picsum.photos/id/1028/800/1000',
      'https://picsum.photos/id/1029/800/1000',
    ],
    category: 'Təmizləmə',
    benefits: [
      'Qara nöqtələri və tıxanmış məsamələri dərindən təmizləyir',
      'Ölü dəri hüceyrələrini aşındırır (pilinq effekti)',
      'Qan dövranını stimullaşdıraraq təbii parlaqlıq bəxş edir',
    ],
    howToUse: 'Dərinizi ilıq su ilə nəmləndirin. Peel rejimini aktivləşdirərək spatula ucunu 45 dərəcə bucaq altında, yüngül təzyiqlə üzünüzdə gəzdirin. Həftədə 2-3 dəfə istifadəsi tövsiyə olunur.',
    ingredients: 'Yüksək tezlikli (24,000 Hz) ultrasəs dalğaları buraxan 100% paslanmayan polad spatula ucluğu və erqonomik suya davamlı IPX5 gövdə.',
    tags: ['YENİ', 'Həftəlik Pilinq'],
    shades: [
      { name: 'Tutqun Qara', colorHex: '#1C1C1C', label: 'Matte Black' },
      { name: 'Zərif Çəhrayı', colorHex: '#ECD5D5', label: 'Soft Pink' },
    ],
  },
  {
    id: 'aluna-eye-glow',
    name: 'ALUNA Eye Radiance Duo',
    subtitle: 'Göz Ətrafı Mikro-Vibrasiya və Termal Masaj Cihazı',
    description: 'Yorğun gözlərə son! 42°C termal masaj və 12,000 vibrasiya/dəq tezlikli sonik masaj başlığı ilə göz ətrafı şişkinlikləri, tünd halqaları azaldır, göz kreminin udulmasını maksimuma çatdırır.',
    price: 89.00,
    originalPrice: 129.00,
    rating: 4.7,
    reviewsCount: 52,
    images: [
      'https://picsum.photos/id/1031/800/1000',
      'https://picsum.photos/id/1032/800/1000',
    ],
    category: 'Göz Qulluğu',
    benefits: [
      'Göz altı torbaları və yorğunluq şişkinliyini dərhal aradan qaldırır',
      'Tünd halqaların rəngini açır və dərini canlandırır',
      'Qaz ayağı qırışlarının dərinliyini azaldır',
    ],
    howToUse: 'Göz ətrafına sevimli göz kreminizi çəkin. Cihazın metal sensor sahəsinə toxunaraq masaj başlığını göz ətrafında daxildən xaricə doğru yumşaq dairəvi hərəkətlərlə hərəkət etdirin.',
    tags: ['Xüsusi Baxım'],
    shades: [
      { name: 'Mirvari Ağ', colorHex: '#F5F5F0', label: 'Pearl White' },
    ],
  },
  {
    id: 'aluna-lift-sculpt',
    name: 'ALUNA Contour Lift V-Sculpt',
    subtitle: 'Yüksək Tezlikli Mikroaxınlı Üz və Boyun Liftinq Aləti',
    description: 'Üz konturlarını mükəmməl şəkildə formaya salan V-formalı dizayn. İkiqat çənə (buxaq) görünüşünü azaldır, almacıq sümüklərini qabardır və boyun qırışlarını hamarlayır.',
    price: 199.00,
    originalPrice: 279.00,
    rating: 4.9,
    reviewsCount: 76,
    images: [
      'https://picsum.photos/id/1033/800/1000',
      'https://picsum.photos/id/1035/800/1000',
    ],
    category: 'Liftinq',
    benefits: [
      'Üz ovalını və çənə xəttini (Jawline) kəskinləşdirir',
      'Buxaq nahiyəsindəki sallanmaları toparlayır',
      'Boyun nahiyəsindəki üfüqi qırışları açır',
    ],
    howToUse: 'Gündə bir dəfə 5-10 dəqiqə ərzində, yuxarıya doğru sürüşdürmə hərəkətləri ilə boyun və çənə xəttinə tətbiq edin. Liftinq gelləri ilə istifadə edildikdə təsiri daha sürətli olur.',
    tags: ['Trend', 'Lüks Seçim'],
    shades: [
      { name: 'Metallik Gümüş', colorHex: '#D3D3D3', label: 'Metallic Silver' },
      { name: 'Premium Qızılı', colorHex: '#D4AF37', label: 'Premium Gold' },
    ],
  },
];

export const REVIEWS: Review[] = [
  {
    id: 'rev-1',
    reviewerName: 'Aytən Məmmədova',
    rating: 5,
    title: 'Möhtəşəm bir investisiya, dərim parıldayır!',
    comment: 'Aluna Radiance Pro-nu təxminən 3 həftədir hər axşam müntəzəm istifadə edirəm. Açığı, evdə bu qədər qısa müddətdə salon effekti alacağımı gözləmirdim. Xüsusilə Qırmızı LED və EMS liftinq rejimi möhtəşəmdir. Üzümdəki yorğunluq tamamilə gedib, dərim çox daha sıx və parlaq görünür. Hər kəs kosmetoloqa getdiyimi soruşur. Çatdırılma da çox sürətli idi, Bakı daxilinə ertəsi gün gətirdilər. Qablaşdırılması isə o qədər premiumdur ki, özünüzü lüks bir salonda hiss edirsiniz.',
    date: '18 İyun 2026',
    location: 'Bakı',
    ageRange: '25-34',
    skinType: 'Quru / Həssas',
    skinTone: 'Açıq',
    verifiedBuyer: true,
    likes: 24,
    dislikes: 0,
  },
  {
    id: 'rev-2',
    reviewerName: 'Günel Qasımova',
    rating: 5,
    title: 'Qara nöqtələrdən birdəfəlik xilas oldum!',
    comment: 'Aluna Sonic Deep Cleanser spatula cihazını aldım və ilk tətbiqdən heyran qaldım. Burnumun üstündəki illərdir keçməyən qara nöqtələri inanılmaz şəkildə təmizlədi. Dərini qətiyyən zədələmir, qızartmır. Həftədə 2 dəfə təmizləyici köpüklə istifadə edirəm. Ölü dərini elə gözəl təmizləyir ki, sonra vurduğum krem dərhal hopur. Qiymətinə tamamilə dəyər bir məhsuldur, kosmetoloqa verilən pullara qənaət etdim.',
    date: '12 İyun 2026',
    location: 'Sumqayıt',
    ageRange: '18-24',
    skinType: 'Yağlı / Akneyə meylli',
    skinTone: 'Buğdayı',
    verifiedBuyer: true,
    likes: 15,
    dislikes: 1,
  },
  {
    id: 'rev-3',
    reviewerName: 'Lalə Əliyeva',
    rating: 5,
    title: 'Göz altı torbalarıma inanılmaz təsiri oldu',
    comment: 'İşimlə əlaqədar olaraq hər gün kompüter arxasındayam və səhərlər gözlərim çox şişkin olurdu. Eye Radiance Duo-nu 10 gündür istifadə edirəm. İsti masaj rejimi dərhal göz ətrafındakı gərginliyi götürür və şişkinliyi endirir. Göz altı kremi ilə birlikdə istifadə edirəm, krem sanki dərinin içinə əriyib daxil olur. Tünd halqalarım da nəzərəçarpacaq dərəcədə açılıb. Çox bəyəndim, rəfiqəmə də hədiyyə sifariş etdim.',
    date: '05 İyun 2026',
    location: 'Gəncə',
    ageRange: '35-44',
    skinType: 'Normal',
    skinTone: 'Açıq',
    verifiedBuyer: true,
    likes: 19,
    dislikes: 0,
  },
  {
    id: 'rev-4',
    reviewerName: 'Nərmin Rzayeva',
    rating: 4,
    title: 'Çənə xəttim daha sıxdır, çox gözəl masaj edir',
    comment: 'Contour Lift V-Sculpt cihazını buxaq nahiyəmi toparlamaq üçün aldım. İki həftəlik istifadədən sonra çənə xəttimdə (jawline) gözlə görülən bir sıxlaşma var. Masajı çox rahatdır, axşamlar televizora baxarkən 10 dəqiqə edirəm. Bir ulduzu yalnız ona görə əskik etdim ki, içindən azərbaycanca təlimat kitabçası çıxmadı, amma saytdakı videolar çox kömək etdi. Ümumi keyfiyyət isə əladır.',
    date: '28 May 2026',
    location: 'Bakı',
    ageRange: '25-34',
    skinType: 'Qarışıq',
    skinTone: 'Buğdayı',
    verifiedBuyer: true,
    likes: 11,
    dislikes: 2,
  },
];

export const FAQS: FAQ[] = [
  {
    id: 'faq-1',
    question: 'Aluna gözəllik cihazlarını hər gün istifadə etmək təhlükəsizdirmi?',
    answer: 'Bəli, cihazlarımızın əksəriyyəti, xüsusilə "Aluna Radiance Pro" LED və mikroaxın rejimləri gündəlik istifadə üçün tamamilə təhlükəsizdir. Lakin ultrases sonik təmizləyici spatula (Sonic Deep Cleanser) kimi dərini aşındıran cihazları həftədə 2-3 dəfədən çox olmamaq şərti ilə istifadə etmək tövsiyə olunur. Hər cihazın özünəməxsus istifadə tezliyi daxili təlimat kitabçasında ətraflı qeyd olunmuşdur.',
    category: 'İstifadə',
  },
  {
    id: 'faq-2',
    question: 'Cihazlar hansı dəri tipləri üçün uyğundur?',
    answer: 'Aluna cihazları bütün dəri tipləri (quru, yağlı, qarışıq, normal və həssas dəri daxil olmaqla) üçün tam uyğundur. LED işıq terapiyası dərinin vəziyyətinə görə tənzimlənir: Göy işıq yağlı və akneyə meylli dərilər üçün idealdır, Qırmızı işıq isə kollageni artırmaq və qırışları azaltmaq istəyən quru və yetkin dərilər üçün mükəmməldir. Həssas dərilər üçün masaj intensivliyini ən aşağı səviyyədən başlamağı tövsiyə edirik.',
    category: 'İstifadə',
  },
  {
    id: 'faq-3',
    question: 'Çatdırılma şərtləriniz necədir? Rayonlara göndəriş var?',
    answer: 'Bəli, çatdırılma xidmətimiz olduqca sürətli və genişdir. Bakı, Sumqayıt və Xırdalan daxilində çatdırılma tamamilə PULSUZDUR və 24 saat ərzində ünvanınıza çatdırılır. Azərbaycanın bütün digər şəhər və rayonlarına isə sifarişiniz 2-3 iş günü ərzində "Azərpoçt" və ya xüsusi kuryer tərəfdaşlarımız vasitəsilə qapıya qədər sürətli şəkildə çatdırılır.',
    category: 'Çatdırılma',
  },
  {
    id: 'faq-4',
    question: 'Aluna məhsullarına rəsmi zəmanət verilirmi?',
    answer: 'Bəli! Aluna olaraq məhsullarımızın keyfiyyətinə tam zəmanət veririk. Bütün gözəllik və masaj cihazlarımıza rəsmi 2 İLLİK ZƏMANƏT təqdim olunur. Hər hansı bir istehsal qüsuru və ya texniki problem yarandıqda, cihazınız tamamilə yenisi ilə əvəz olunur və ya ödənişsiz təmir edilir.',
    category: 'Zəmanət',
  },
  {
    id: 'faq-5',
    question: 'Hamiləlik və ya digər tibbi vəziyyətlərdə istifadə etmək olarmı?',
    answer: 'LED işıq terapiyası və yüngül vibrasiya rejimləri hamiləlik zamanı zərərsiz olsa da, mikroaxın (EMS) texnologiyalı rejimlərin hamiləlik müddətində, bədənində kardiostimulyator (kardio-aparat) olan şəxslərdə və ya ağır onkoloji xəstəliklərdən əziyyət çəkənlərdə istifadəsi tövsiyə olunmur. Hər hansı şübhə yarandıqda, istifadədən öncə şəxsi həkiminizlə məsləhətləşməyiniz vacibdir.',
    category: 'Təhlükəsizlik',
  },
];

export const RITUAL_STEPS = [
  {
    stepNumber: 1,
    title: 'DƏRİN ULTRASES TƏMİZLƏMƏ',
    subtitle: 'ALUNA Sonic Deep Cleanser',
    description: 'Üzünüzü yuyun, nəmli saxlayın. Spatulamızın ultrasəs dalğaları ilə məsamələri dərindən açın, qara nöqtələri və ölü hüceyrələri yumşaqca aşındırın.',
    image: 'https://picsum.photos/id/1028/800/800',
    actionText: 'CİHAZI KƏŞF ET',
    href: '#aluna-ultrasonic-clean',
  },
  {
    stepNumber: 2,
    title: 'AKTİV SERUM VƏ ABSORBSİYA',
    subtitle: 'Aluna Qulluq Serumu ilə birlikdə',
    description: 'Aluna hialuron və kollagen tərkibli serumu üzünüzə bərabər yayın. İsti kompres rejimi serumun dərinin altına 3 qat daha sürətli hopmasını təmin edəcək.',
    image: 'https://picsum.photos/id/1025/800/800',
    actionText: 'SERUMU KƏŞF ET',
    href: '#skincare',
  },
  {
    stepNumber: 3,
    title: 'MİKROAXIN MASAJI VƏ LİFTİNQ',
    subtitle: 'ALUNA Contour V-Sculpt',
    description: 'EMS mikroaxınları ilə üz əzələlərini hərəkətə gətirin. Almacıq sümüklərini qabardın, çənə konturunu (jawline) sıxlaşdırın və üz ovalını formalaşdırın.',
    image: 'https://picsum.photos/id/1033/800/800',
    actionText: 'LİFTİNQ CİHAZINI GÖR',
    href: '#aluna-lift-sculpt',
  },
  {
    stepNumber: 4,
    title: 'LED TERAPİYA İLƏ CAVANLAŞMA',
    subtitle: 'ALUNA Radiance Pro',
    description: 'Qırmızı LED işığı ilə kollagen istehsalını artırın, hüceyrə regenerasiyasını stimullaşdıraraq qırışları hamarlayın və dərini parlaq edin.',
    image: 'https://picsum.photos/id/1027/800/800',
    actionText: 'MED-LED CİHAZINI GÖR',
    href: '#aluna-radiance-pro',
  },
];

export const BENEFITS_LIST: Benefit[] = [
  {
    id: 'ben-1',
    title: 'Evdə Salon Komfortu',
    description: 'Bahalı gözəllik salonu prosedurlarını öz evinizdə, istədiyiniz vaxt, peşəkar səviyyədə həyata keçirin.',
    iconName: 'Home',
  },
  {
    id: 'ben-2',
    title: 'Dərhal Görünən Nəticələr',
    description: 'Dərinin şişkinliyinin enməsi, parlaqlıq və hamarlıq ilk tətbiqdən dərhal sonra aydın hiss olunur.',
    iconName: 'Zap',
  },
  {
    id: 'ben-3',
    title: 'Hipoallergik və Təhlükəsiz',
    description: 'Həssas dərilər daxil olmaqla, hər kəsin rahatlıqla istifadə edə biləcəyi tibbi dərəcəli materiallar və texnologiya.',
    iconName: 'ShieldCheck',
  },
  {
    id: 'ben-4',
    title: 'Zəmanət və Texniki Dəstək',
    description: 'Bütün Aluna cihazlarına 2 illik tam zəmanət təqdim edirik. Problemsiz dəyişdirmə və dəstək xidməti.',
    iconName: 'HeartHandshake',
  },
];
